### ISSUE TITLE
Can't set minimal mode with icons in desktop

### ISSUE THREAD

**Issue by jruizsulime** [4xmen/rvnm#2]
I've tried to put the menu in minimal mode by default, but when i set mode 'minimal' in the js file, menu is mobile with no icons only the burger one.

How to set minimal menú showing all icons (no labels) with submenu on icon-hover ?

thanks so much.

**Comment by A1Gard** [comment]
We have an `ltr` example in `demo/index.html`, You can find there a comment about `setMode`, Here is uncommented sample:

```javascript
         $(function () {
                var rvnMenu = $("#navbar").rvnm({
                    searchable: true,
                    theme: 'dark-lesb',
                    sticky: 2,
                });
                console.log(rvnMenu);
                rvnMenu.setMode('minimal'); // uncommented line
                rvnMenu.setTheme('dark-ruby');
            });
```

BTW don't forget use `@fortawesome/fontawesome-free` dependency `all.min.css`.

**Comment by amir1428** [comment]
8ff5a4cc6f51e138938e56c7a3324e2bdd4f576d
